name: fruit_dashbord
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter_localizations:
    sdk: flutter
  firebase_core: ^3.9.0
  flutter:
    sdk: flutter

  image_picker: ^1.1.2
  skeletonizer: ^1.4.2
  dartz: ^0.10.1
  modal_progress_hud_nsn: ^0.5.1
  get_it: ^8.0.2
  firebase_storage: ^12.3.7
  cloud_firestore: ^5.5.0
  path: ^1.9.0
  flutter_bloc: ^8.1.6
  supabase_flutter: ^2.8.3

dev_dependencies:

  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
flutter_intl:
  enabled: true
